yupao:
  uploadPath: D:/yupao/uploadPath
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    urlPrefix: http://yupao-project-ichensw.oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tF4yknHS8v7yLrkB8mh
    accessKeySecret: Q3XYGDvyDDMYAVZJvGqyXz3lgOUSPi
    bucketName: yupao-project-ichensw
    fileHost: files

spring:
  profiles:
    active: dev
  application:
    name: yupao-backend
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/yupao
#    username: root
#    password: root
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.70.63.241:3306/yupao
    username: yupao
    password: dxeXNRHsm8nWHAFM
  # session失效时间
  session:
    timeout: 1800
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
  devtools:
    restart:
      enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
logging:
  level:
    cn:
      ichensw:
        yupao:
          mapper: debug
mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
